name: test
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1
      - uses: actions/checkout@v1
      - run: go test -v
      - run: go test -v -tags='readme_example'
